// src/lib/questions.ts
export type BlockId =
  | "social"
  | "communication"
  | "repetitive"
  | "sensory"
  | "play"
  | "daily";
export type AgeBand = "2-3" | "4-5" | "6-7";
export type Direction = "positive" | "negative";

export type Question = {
  id: string;
  block: BlockId;
  text: string;
  example: string;
  explain: string;
  bands: AgeBand[];
  // ASD uchun “yadro” (core) savollar
  isCoreFlag?: boolean;
  // kritik savol (tezkor eskalatsiya)
  isRedFlag?: boolean;
  // positive: ko‘nikma bor (Ko‘pincha = yaxshi)
  // negative: muammo belgisi (Ko‘pincha = yomon)
  direction: Direction;
};

export const BLOCKS: { id: BlockId; title: string; subtitle: string }[] = [
  { id: "social", title: "Ijtimoiy aloqa", subtitle: "Ko‘z kontakt, ismga javob, joint attention" },
  { id: "communication", title: "Nutq va muloqot", subtitle: "Tushunish, javob berish, intonatsiya" },
  { id: "repetitive", title: "Takroriy harakatlar", subtitle: "Stereotipiya, rutina, qiziqishlar" },
  { id: "sensory", title: "Sensor sezgirlik", subtitle: "Tovush, teginish, yorug‘lik, hid" },
  { id: "play", title: "O‘yin va tasavvur", subtitle: "Rol o‘yinlari, syujet, ijtimoiy o‘yin" },
  { id: "daily", title: "Kundalik hayot", subtitle: "Moslashuv, mustaqillik, emotsional regulyatsiya" },
];

// 96 savol (6 blok)
export const QUESTIONS: Question[] = [
  // 1-BLOK: IJTIMOIY ALOQA (18)
  // 👶 1.5–3 yosh
  {
    id: "S1",
    block: "social",
    text: "Ismi aytilganda javob beradimi?",
    example: "Ismini chaqirganda qaraydi, tovush chiqaradi yoki yoningizga keladi.",
    explain: "Ismga reaksiya ijtimoiy e’tibor va muloqotning erta belgisi hisoblanadi.",
    bands: ["2-3"],
    isCoreFlag: true,
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "S2",
    block: "social",
    text: "Ko‘z bilan aloqa qiladimi?",
    example: "Siz gapirganda yuzingizga qaraydi.",
    explain: "Ko‘z bilan aloqa ijtimoiy bog‘lanishning muhim ko‘rsatkichi.",
    bands: ["2-3"],
    isCoreFlag: true,
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "S3",
    block: "social",
    text: "Quvonchni bo‘lishishga harakat qiladimi?",
    example: "Qiziqarli narsani ko‘rsatadi yoki kulib sizga qaraydi.",
    explain: "Birgalikdagi e’tibor (joint attention) autizmda ko‘pincha zaif bo‘ladi.",
    bands: ["2-3"],
    isCoreFlag: true,
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "S4",
    block: "social",
    text: "Ijtimoiy tabassum bormi?",
    example: "Siz kulganda javoban kuladi.",
    explain: "Ijtimoiy tabassum emotsional javobni ko‘rsatadi.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "S5",
    block: "social",
    text: "Imo-ishoralardan foydalanadimi?",
    example: "Biror narsani barmog‘i bilan ko‘rsatadi.",
    explain: "Imo-ishoralar nutqdan oldingi muhim muloqot vositasidir.",
    bands: ["2-3"],
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "S6",
    block: "social",
    text: "Kattalar bilan aloqa qilishdan qochadimi?",
    example: "Odamlar yaqinlashsa chetga chiqib ketadi.",
    explain: "Ijtimoiy chekinish autizmga xos belgilaridan biri bo‘lishi mumkin.",
    bands: ["2-3"],
    direction: "negative",
  },
  // 👧 4–5 yosh
  {
    id: "S7",
    block: "social",
    text: "Boshqa bolalarga qiziqish bildiradimi?",
    example: "O‘yin maydonchasida bolalar yoniga boradi.",
    explain: "Tengdoshlar bilan qiziqish ijtimoiy rivojlanish belgisi.",
    bands: ["4-5"],
    isCoreFlag: true,
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "S8",
    block: "social",
    text: "O‘yin vaqtida navbatni tushunadimi?",
    example: "“Avval sen, keyin men” qoidalariga amal qiladi.",
    explain: "Navbat kutish ijtimoiy qoidalarni tushunish bilan bog‘liq.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "S9",
    block: "social",
    text: "His-tuyg‘ularga javob qaytaradimi?",
    example: "Siz xafa bo‘lsangiz, sezib reaksiya bildiradi.",
    explain: "Emotsional empatiya ijtimoiy tushunishni ko‘rsatadi.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "S10",
    block: "social",
    text: "Ko‘z bilan aloqa suhbat davomida saqlanadimi?",
    example: "Gaplashayotganda yuzingizga qarab turadi.",
    explain: "Uzoqroq ko‘z aloqasi yoshga mos rivoj belgisi.",
    bands: ["4-5"],
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "S11",
    block: "social",
    text: "Ijtimoiy vaziyatga moslashadimi?",
    example: "Mehmon kelganda o‘zini boshqacha tutadi.",
    explain: "Moslashuvchanlik ijtimoiy idrok bilan bog‘liq.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "S12",
    block: "social",
    text: "Ijtimoiy vaziyatlardan chekinadimi?",
    example: "Bayram yoki bog‘chada yolg‘iz qoladi.",
    explain: "Ijtimoiy chekinish muhim signal bo‘lishi mumkin.",
    bands: ["4-5"],
    direction: "negative",
  },
  // 👦 6–7 yosh
  {
    id: "S13",
    block: "social",
    text: "Do‘st orttirishga harakat qiladimi?",
    example: "O‘zi o‘ynashga taklif qiladi.",
    explain: "Ijtimoiy tashabbus muhim ko‘rsatkichdir.",
    bands: ["6-7"],
    isCoreFlag: true,
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "S14",
    block: "social",
    text: "Guruh qoidalariga amal qiladimi?",
    example: "Sinf yoki o‘yin qoidalarini bajaradi.",
    explain: "Qoidalarni tushunish ijtimoiy moslashuvni ko‘rsatadi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "S15",
    block: "social",
    text: "Boshqalarning hissiyotini tushunadimi?",
    example: "Do‘sti xafa bo‘lsa, sezadi.",
    explain: "Empatiya autizmda ko‘pincha zaif bo‘ladi.",
    bands: ["6-7"],
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "S16",
    block: "social",
    text: "Ijtimoiy hazilni tushunadimi?",
    example: "Oddiy hazillarga kuladi.",
    explain: "Hazilni tushunish ijtimoiy tafakkur bilan bog‘liq.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "S17",
    block: "social",
    text: "Kattalar bilan muloqoti mosmi?",
    example: "O‘qituvchi bilan muloyim gaplashadi.",
    explain: "Yoshga mos ijtimoiy xulq baholanadi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "S18",
    block: "social",
    text: "Ijtimoiy vaziyatlardan qochadimi?",
    example: "Tadbir va jamoaviy o‘yinlardan bosh tortadi.",
    explain: "Doimiy qochish xavf belgisi bo‘lishi mumkin.",
    bands: ["6-7"],
    direction: "negative",
  },

  // 2-BLOK: NUTQ VA MULOQOT (18)
  // 👶 1.5–3 yosh
  {
    id: "C1",
    block: "communication",
    text: "So‘z yoki qisqa iboralarni ishlatadimi?",
    example: "“ber”, “mama kel”, “yana” kabi so‘zlarni aytadi.",
    explain: "Nutqning paydo bo‘lishi muloqot rivojining asosiy bosqichidir.",
    bands: ["2-3"],
    isCoreFlag: true,
    direction: "positive",
  },
  {
    id: "C2",
    block: "communication",
    text: "So‘zlarni maqsadli ishlatadimi?",
    example: "Suv so‘rab “suv” deydi, shunchaki takrorlamaydi.",
    explain: "Maqsadli nutq muloqot niyatini ko‘rsatadi.",
    bands: ["2-3"],
    isCoreFlag: true,
    direction: "positive",
  },
  {
    id: "C3",
    block: "communication",
    text: "Oddiy topshiriqlarni tushunadimi?",
    example: "“Koptokni olib kel” deganda bajaradi.",
    explain: "Nutqni tushunish (reseptiv nutq) muhim rivoj belgisi.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "C4",
    block: "communication",
    text: "Nutq o‘rniga faqat harakatdan foydalanadimi?",
    example: "So‘ramay qo‘lingizdan tortadi.",
    explain: "Nutq o‘rnini harakat bosishi kechikish belgisi bo‘lishi mumkin.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "C5",
    block: "communication",
    text: "Ovozi hissiyotga mosmi?",
    example: "Xursand bo‘lsa ovozi quvonchli chiqadi.",
    explain: "Intonatsiya emotsional muloqot bilan bog‘liq.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "C6",
    block: "communication",
    text: "So‘zlarni ma’nosiz takrorlaydimi?",
    example: "Eshitgan gapni tushunmasdan qaytaradi.",
    explain: "Ekolaliya autizmda ko‘p uchraydi.",
    bands: ["2-3"],
    direction: "negative",
  },
  // 👧 4–5 yosh
  {
    id: "C7",
    block: "communication",
    text: "Gaplari tushunarli va mantiqlimi?",
    example: "Bo‘lib o‘tgan voqeani tushuntirib bera oladi.",
    explain: "Mantiqli nutq fikrlash rivojini ko‘rsatadi.",
    bands: ["4-5"],
    isCoreFlag: true,
    direction: "positive",
  },
  {
    id: "C8",
    block: "communication",
    text: "Savollarga mos javob beradimi?",
    example: "“Bog‘chada nima qilding?” deganda javob beradi.",
    explain: "Savol-javob muloqotning muhim ko‘nikmasi.",
    bands: ["4-5"],
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "C9",
    block: "communication",
    text: "Suhbatni davom ettira oladimi?",
    example: "Savolga javob berib, qo‘shimcha gap aytadi.",
    explain: "Suhbatni ushlab turish ijtimoiy nutq belgisi.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "C10",
    block: "communication",
    text: "Nutq ohangi noodatiymi?",
    example: "Bir xil ohangda gapiradi.",
    explain: "Monoton nutq autizmga xos bo‘lishi mumkin.",
    bands: ["4-5"],
    direction: "negative",
  },
  {
    id: "C11",
    block: "communication",
    text: "So‘z boyligi yoshiga mosmi?",
    example: "Ranglar, buyumlar nomini biladi.",
    explain: "Lug‘at boyligi kognitiv rivoj bilan bog‘liq.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "C12",
    block: "communication",
    text: "Ekolaliya kuzatiladimi?",
    example: "Multfilm replikalarini qayta-qayta aytadi.",
    explain: "Takroriy nutq muloqotni cheklaydi.",
    bands: ["4-5"],
    isRedFlag: true,
    direction: "negative",
  },
  // 👦 6–7 yosh
  {
    id: "C13",
    block: "communication",
    text: "Suhbatni mustaqil boshlay oladimi?",
    example: "O‘zi savol beradi yoki gap ochadi.",
    explain: "Tashabbus ijtimoiy nutqning belgisi.",
    bands: ["6-7"],
    isCoreFlag: true,
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "C14",
    block: "communication",
    text: "Mavzuni saqlab qoladimi?",
    example: "Gapni boshqa tomonga og‘dirib yubormaydi.",
    explain: "Mavzuni saqlash diqqat va muloqot bilan bog‘liq.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "C15",
    block: "communication",
    text: "Nutqi haddan ortiq rasmiy emasmi?",
    example: "Kattalardek rasmiy iboralar ishlatadi.",
    explain: "Noodatiy nutq uslubi autizm belgisi bo‘lishi mumkin.",
    bands: ["6-7"],
    direction: "negative",
  },
  {
    id: "C16",
    block: "communication",
    text: "Savollarga qisqa javob beradimi?",
    example: "Faqat “ha/yo‘q” bilan cheklanadi.",
    explain: "Cheklangan nutq muloqot qiyinchiligini ko‘rsatadi.",
    bands: ["6-7"],
    direction: "negative",
  },
  {
    id: "C17",
    block: "communication",
    text: "Nutq orqali ijtimoiy aloqa qura oladimi?",
    example: "O‘rtoqlari bilan kelishib o‘ynaydi.",
    explain: "Nutq – ijtimoiy moslashuv vositasi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "C18",
    block: "communication",
    text: "Nutqi monologga o‘xshaydimi?",
    example: "O‘zi gapiradi, boshqani tinglamaydi.",
    explain: "Ikki tomonlama muloqot buzilishi mumkin.",
    bands: ["6-7"],
    isRedFlag: true,
    direction: "negative",
  },

  // 3-BLOK: TAKRORIY HARAKATLAR (6, barcha yosh)
  {
    id: "R1",
    block: "repetitive",
    text: "Takroriy tana harakatlari qiladimi?",
    example: "Qo‘l siltaydi, aylanadi.",
    explain: "Stereotipik harakatlar erta belgidir.",
    bands: ["2-3", "4-5", "6-7"],
    direction: "negative",
  },
  {
    id: "R2",
    block: "repetitive",
    text: "Buyumlarni aylantiradimi?",
    example: "G‘ildirakni uzoq aylantiradi.",
    explain: "Funksional bo‘lmagan o‘yin alomati.",
    bands: ["2-3", "4-5", "6-7"],
    direction: "negative",
  },
  {
    id: "R3",
    block: "repetitive",
    text: "Bir xil o‘yinni takrorlaydimi?",
    example: "Faqat mashinani u yoq-bu yoqqa suradi.",
    explain: "Qiziqish cheklangan bo‘lishi mumkin.",
    bands: ["2-3", "4-5", "6-7"],
    direction: "negative",
  },
  {
    id: "R4",
    block: "repetitive",
    text: "Tartib buzilsa bezovta bo‘ladimi?",
    example: "Marshrut o‘zgarsa yig‘laydi.",
    explain: "Moslashuv qiyinligi.",
    bands: ["2-3", "4-5", "6-7"],
    direction: "negative",
  },
  {
    id: "R5",
    block: "repetitive",
    text: "O‘yinchoqni noodatiy ishlatadimi?",
    example: "Tishlaydi yoki faqat qatorlaydi.",
    explain: "O‘yin funksiyasi buzilishi mumkin.",
    bands: ["2-3", "4-5", "6-7"],
    direction: "negative",
  },
  {
    id: "R6",
    block: "repetitive",
    text: "Stressda bu harakatlar kuchayadimi?",
    example: "Qo‘rqsa ko‘proq siltaydi.",
    explain: "Stress bilan bog‘liqlik muhim.",
    bands: ["2-3", "4-5", "6-7"],
    direction: "negative",
  },

  // 4-BLOK: SENSOR SEZGIRLIK (18)
  // 👶 1.5–3 yosh
  {
    id: "N1",
    block: "sensory",
    text: "Baland tovushlardan cho‘chiydimi?",
    example: "Changyutgich, blender yoki eshik qarsillashidan qo‘rqadi.",
    explain: "Sensor tovushlarga haddan ortiq reaksiya autizmda tez-tez uchraydi.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "N2",
    block: "sensory",
    text: "Ayrim kiyimlarni kiyishni yoqtirmaydimi?",
    example: "Yangi kiyim kiydirganda yechishga harakat qiladi.",
    explain: "Teri sezgirligi sensor integratsiya bilan bog‘liq.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "N3",
    block: "sensory",
    text: "Ba’zi ovqatlardan keskin bosh tortadimi?",
    example: "Faqat ma’lum teksturadagi ovqatni yeydi.",
    explain: "Sensor sezgirlik ovqatlanish xulqiga ta’sir qilishi mumkin.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "N4",
    block: "sensory",
    text: "Og‘riqqa noodatiy reaksiya qiladimi?",
    example: "Yiqlansa ham yig‘lamaydi yoki juda kuchli reaksiya qiladi.",
    explain: "Og‘riq sezishdagi farq muhim signal hisoblanadi.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "N5",
    block: "sensory",
    text: "Ayrim hidlardan bezovta bo‘ladimi?",
    example: "Atir yoki ovqat hididan yuzini buradi.",
    explain: "Hid sezgirligi sensor tizim bilan bog‘liq.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "N6",
    block: "sensory",
    text: "Sensor bezovtalik kundalik hayotga halaqit beradimi?",
    example: "Tovush sabab uxlash yoki ovqatlanish qiyinlashadi.",
    explain: "Kundalik faoliyatga ta’siri muhim baholash mezoni.",
    bands: ["2-3"],
    direction: "negative",
  },
  // 👧 4–5 yosh
  {
    id: "N7",
    block: "sensory",
    text: "Shovqinli joylarda bezovta bo‘ladimi?",
    example: "Bog‘cha tadbirlarida quloqlarini yopadi.",
    explain: "Sensor yuklama oshganda qiyinchilik yuzaga chiqadi.",
    bands: ["4-5"],
    direction: "negative",
  },
  {
    id: "N8",
    block: "sensory",
    text: "Yorug‘likka sezgirlik bormi?",
    example: "Juda yorug‘ xonada ko‘zini qisadi.",
    explain: "Vizual sezgirlik autizm spektrida kuzatiladi.",
    bands: ["4-5"],
    direction: "negative",
  },
  {
    id: "N9",
    block: "sensory",
    text: "Kiyim teginishidan norozilik bildiradimi?",
    example: "Yorliq yoki chokdan shikoyat qiladi.",
    explain: "Taktik sezgirlik ijtimoiy qulaylikka ta’sir qiladi.",
    bands: ["4-5"],
    direction: "negative",
  },
  {
    id: "N10",
    block: "sensory",
    text: "Og‘riqqa reaksiya g‘ayrioddiy emasmi?",
    example: "Kichik jarohatga haddan ortiq reaksiya.",
    explain: "Sensor qayta ishlash farqlari bilan bog‘liq.",
    bands: ["4-5"],
    direction: "negative",
  },
  {
    id: "N11",
    block: "sensory",
    text: "Ayrim tovushlarni yoqtirmaydimi?",
    example: "Soatning “tik-tik” ovozidan bezovta bo‘ladi.",
    explain: "Ma’lum tovushlarga selektiv sezgirlik muhim belgidir.",
    bands: ["4-5"],
    direction: "negative",
  },
  {
    id: "N12",
    block: "sensory",
    text: "Sensor muhitda o‘zini tinchlantira olmaydimi?",
    example: "Shovqinda yig‘lab qoladi yoki chetga chiqadi.",
    explain: "O‘zini boshqarish qobiliyati baholanadi.",
    bands: ["4-5"],
    direction: "negative",
  },
  // 👦 6–7 yosh
  {
    id: "N13",
    block: "sensory",
    text: "Maktab muhitida sensor qiyinchilik bormi?",
    example: "Sinf shovqinidan tez charchaydi.",
    explain: "Sensor yuklama o‘qishga ta’sir qilishi mumkin.",
    bands: ["6-7"],
    direction: "negative",
  },
  {
    id: "N14",
    block: "sensory",
    text: "Tovush yoki yorug‘likka haddan ortiq e’tibor beradimi?",
    example: "Mayda tovushlarga ham chalg‘iydi.",
    explain: "Sensor filtratsiya qiyinligi belgisi.",
    bands: ["6-7"],
    direction: "negative",
  },
  {
    id: "N15",
    block: "sensory",
    text: "Kiyim yoki materiallarga nisbatan tanlovchanmi?",
    example: "Faqat ma’lum matoni kiyadi.",
    explain: "Sensor afzalliklar ijtimoiy moslashuvga ta’sir qiladi.",
    bands: ["6-7"],
    direction: "negative",
  },
  {
    id: "N16",
    block: "sensory",
    text: "Og‘riqni noto‘g‘ri baholaydimi?",
    example: "Jiddiy jarohatni e’tiborsiz qoldiradi.",
    explain: "Xavfsizlik nuqtayi nazaridan muhim.",
    bands: ["6-7"],
    direction: "negative",
  },
  {
    id: "N17",
    block: "sensory",
    text: "Sensor bezovtalik stressni kuchaytiradimi?",
    example: "Shovqinda jahli tez chiqadi.",
    explain: "Stress–sensor bog‘liqligi baholanadi.",
    bands: ["6-7"],
    direction: "negative",
  },
  {
    id: "N18",
    block: "sensory",
    text: "Sensor qiyinchiliklar kundalik faoliyatni cheklaydimi?",
    example: "Maktab yoki jamoat joyidan qochadi.",
    explain: "Hayot sifatiga ta’siri muhim.",
    bands: ["6-7"],
    direction: "negative",
  },

  // 5-BLOK: O‘YIN VA TASAVVUR (18)
  // 👶 1.5–3 yosh
  {
    id: "P1",
    block: "play",
    text: "O‘yinchoqlarni maqsadli ishlatadimi?",
    example: "Mashinani yurgizadi, qoshiq bilan ovqat “beradi”.",
    explain: "Funksional o‘yin kognitiv rivoj belgisi.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "P2",
    block: "play",
    text: "Rolli o‘yin alomatlari bormi?",
    example: "Qo‘g‘irchoqni uxlatadi.",
    explain: "Tasavvuriy o‘yin autizmda ko‘pincha cheklangan.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "P3",
    block: "play",
    text: "O‘yinda sizni jalb qiladimi?",
    example: "O‘ynashga chaqiradi.",
    explain: "Birgalikdagi o‘yin ijtimoiy bog‘lanishni ko‘rsatadi.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "P4",
    block: "play",
    text: "O‘yinlar xilma-xilmi?",
    example: "Birgina o‘yinga yopishib olmaydi.",
    explain: "Xilma-xillik moslashuvchanlik belgisi.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "P5",
    block: "play",
    text: "O‘yinda ijodkorlik bormi?",
    example: "Buyumni boshqa maqsadda ishlatadi.",
    explain: "Tasavvur rivoji baholanadi.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "P6",
    block: "play",
    text: "O‘yin mexanik va takroriy emasmi?",
    example: "Faqat qatorlab qo‘yadi.",
    explain: "Mexanik o‘yin autizmga xos.",
    bands: ["2-3"],
    direction: "positive",
  },
  // 👧 4–5 yosh
  {
    id: "P7",
    block: "play",
    text: "Rolli o‘yinlarni mustaqil o‘ynaydimi?",
    example: "“Do‘kon”, “shifokor” o‘ynaydi.",
    explain: "Ijtimoiy tasavvur rivojlanganini ko‘rsatadi.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "P8",
    block: "play",
    text: "O‘yin syujeti bormi?",
    example: "O‘yinda voqea ketma-ketligi mavjud.",
    explain: "Kognitiv rejalashtirish bilan bog‘liq.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "P9",
    block: "play",
    text: "O‘yin vaqtida qoidalarni tushunadimi?",
    example: "Navbat kutadi, “endi sen, keyin men”.",
    explain: "Qoidalarga rioya qilish moslashuv belgisi.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "P10",
    block: "play",
    text: "O‘yinda rollarni almashtiradimi?",
    example: "Bugun haydovchi, keyin yo‘lovchi bo‘ladi.",
    explain: "Moslashuvchan tafakkur baholanadi.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "P11",
    block: "play",
    text: "Boshqa bolalar bilan o‘ynaydimi?",
    example: "Guruh o‘yiniga qo‘shiladi.",
    explain: "Ijtimoiy o‘yin muhim mezon.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "P12",
    block: "play",
    text: "O‘yin juda cheklangan emasmi?",
    example: "Faqat bitta mavzuni tanlaydi.",
    explain: "Qiziqish torligi baholanadi.",
    bands: ["4-5"],
    direction: "positive",
  },
  // 👦 6–7 yosh
  {
    id: "P13",
    block: "play",
    text: "Qoidalarga asoslangan o‘yinlarni tushunadimi?",
    example: "Stol o‘yinlari qoidalariga amal qiladi.",
    explain: "Kognitiv va ijtimoiy rivoj belgisi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "P14",
    block: "play",
    text: "O‘yin davomida moslashuvchanmi?",
    example: "Qoidalar biroz o‘zgarsa qabul qiladi.",
    explain: "Moslashuv autizmda qiyin bo‘lishi mumkin.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "P15",
    block: "play",
    text: "Tasavvuriy o‘yin yoshiga mosmi?",
    example: "Murakkab syujetli o‘yinlar o‘ynaydi.",
    explain: "Tasavvur rivoji baholanadi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "P16",
    block: "play",
    text: "Jamoaviy o‘yinda faolmi?",
    example: "Guruh bilan kelishib o‘ynaydi.",
    explain: "Hamkorlik muhim ijtimoiy ko‘nikma.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "P17",
    block: "play",
    text: "O‘yin davomida muloqot qiladimi?",
    example: "O‘yin jarayonida gaplashadi.",
    explain: "O‘yin va nutq integratsiyasi baholanadi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "P18",
    block: "play",
    text: "O‘yin qattiq stereotipik emasmi?",
    example: "Har safar bir xil ssenariy.",
    explain: "Stereotipiya autizm belgisi.",
    bands: ["6-7"],
    direction: "positive",
  },

  // 6-BLOK: KUNDALIK HAYOT (18)
  // 👶 1.5–3 yosh
  {
    id: "D1",
    block: "daily",
    text: "Ovqatlanishda qiyinchilik bormi?",
    example: "Juda tanlab yeydi.",
    explain: "Kundalik moslashuv baholanadi.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "D2",
    block: "daily",
    text: "Uxlash tartibi buzilganmi?",
    example: "Kech uxlaydi, tez uyg‘onadi.",
    explain: "Uyqu rivojlanishga ta’sir qiladi.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "D3",
    block: "daily",
    text: "O‘zini tinchlantira oladimi?",
    example: "Yig‘lab uzoq tinchimaydi.",
    explain: "Emotsional regulyatsiya muhim.",
    bands: ["2-3"],
    isRedFlag: true,
    direction: "positive",
  },
  {
    id: "D4",
    block: "daily",
    text: "Kundalik rejimga moslashadimi?",
    example: "Hammom, ovqat vaqtiga ko‘nikadi.",
    explain: "Strukturani qabul qilish baholanadi.",
    bands: ["2-3"],
    direction: "positive",
  },
  {
    id: "D5",
    block: "daily",
    text: "Yangi vaziyatga reaksiya qiyinmi?",
    example: "Yangi joyda qattiq bezovta bo‘ladi.",
    explain: "Moslashuv qiyinligi belgisi.",
    bands: ["2-3"],
    direction: "negative",
  },
  {
    id: "D6",
    block: "daily",
    text: "Kundalik qiyinchiliklar stress bilan kuchayadimi?",
    example: "Charchaganda xulqi yomonlashadi.",
    explain: "Stressga bog‘liqlik muhim.",
    bands: ["2-3"],
    direction: "negative",
  },
  // 👧 4–5 yosh
  {
    id: "D7",
    block: "daily",
    text: "O‘ziga xizmat qilish ko‘nikmalari bormi?",
    example: "O‘zi kiyinishga harakat qiladi.",
    explain: "Mustaqillik darajasi baholanadi.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "D8",
    block: "daily",
    text: "Kundalik tartibni tushunadimi?",
    example: "Bog‘chadagi rejimga moslashadi.",
    explain: "Strukturaga moslashuv muhim.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "D9",
    block: "daily",
    text: "O‘zgarishlarni qabul qiladimi?",
    example: "Reja o‘zgarsa qattiq norozilik qilmaydi.",
    explain: "Moslashuvchanlik belgisi.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "D10",
    block: "daily",
    text: "O‘z xulqini boshqara oladimi?",
    example: "Jahli chiqsa tez tinchlanadi.",
    explain: "Emotsional nazorat baholanadi.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "D11",
    block: "daily",
    text: "Mustaqil vazifalarni bajara oladimi?",
    example: "O‘yinchoqlarni yig‘ishtiradi.",
    explain: "Ijro funksiyasi rivoji.",
    bands: ["4-5"],
    direction: "positive",
  },
  {
    id: "D12",
    block: "daily",
    text: "Kundalik faoliyatda doimiy qiyinchilik bormi?",
    example: "Oddiy vazifalar ham qiyin.",
    explain: "Hayot sifatiga ta’siri muhim.",
    bands: ["4-5"],
    isRedFlag: true,
    direction: "negative",
  },
  // 👦 6–7 yosh
  {
    id: "D13",
    block: "daily",
    text: "Maktabga tayyorgarlik darajasi qanday?",
    example: "Darsda o‘tirib tinglay oladi.",
    explain: "Akademik va ijtimoiy tayyorgarlik baholanadi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "D14",
    block: "daily",
    text: "Mustaqillik darajasi yoshiga mosmi?",
    example: "O‘zi kiyinish, yig‘inishni biladi.",
    explain: "Kundalik hayot ko‘nikmalari muhim.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "D15",
    block: "daily",
    text: "Mas’uliyatni tushunadimi?",
    example: "Uy vazifasini bajarishga harakat qiladi.",
    explain: "Ijro va rejalashtirish baholanadi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "D16",
    block: "daily",
    text: "O‘zgarishlarga moslashadimi?",
    example: "Dars jadvali o‘zgarsa qabul qiladi.",
    explain: "Moslashuv autizmda qiyin bo‘lishi mumkin.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "D17",
    block: "daily",
    text: "Stressni boshqara oladimi?",
    example: "Qiyin vaziyatda o‘zini tutadi.",
    explain: "Emotsional regulyatsiya baholanadi.",
    bands: ["6-7"],
    direction: "positive",
  },
  {
    id: "D18",
    block: "daily",
    text: "Kundalik qiyinchiliklar ijtimoiy hayotga ta’sir qiladimi?",
    example: "Maktabga borishdan bosh tortadi.",
    explain: "Funktsional ta’sir eng muhim mezon.",
    bands: ["6-7"],
    isRedFlag: true,
    direction: "negative",
  },
];

export function ageToBand(ageYears: number): AgeBand {
  if (ageYears <= 3) return "2-3";
  if (ageYears <= 5) return "4-5";
  return "6-7";
}
